# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab0659f708b7f2f7f45ef4d57aaa24855d18a1563f73d1e77b7950a7bf3360eb47863f4050af369536c8c63a33397e3753c636f5ab7decf63881856ba5a4e338

test:
  secret_key_base: 23a57ef3b47e0c040938cd815c1f98cd5665c2ef29a064229cae6d2f364af6d181b316689f7aee563c5c4be58c91609641f6fa9947d7a841a012379d70b04644

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
